import { UserState } from '../stores/StoreTypes';

export const dummyUser: UserState = {
	personalInfo: {
		id: 'user_006',
		name: 'Jane Doe',
		username: 'jane_doe32',
		email: 'jane.doe@example.com',
		imageId: 'image_943',
		verified: true,
		premium: true,
	},
	quotas: {
		leftAdQuota: 12,
		leftFreeImageQuota: 2,
	},
	social: {
		socialMedia: [
			{
				social: 'instagram',
				url: 'https://instagram.com/janedoe',
				username: 'test3',
			},
			{
				social: 'twitter',
				url: 'https://twitter.com/janedoe',
				username: 'test33',
			},
			{
				social: 'youtube',
				url: 'https://twitter.com/janedoe',
				username: 'test31',
			},
			{
				social: 'discord',
				url: 'https://twitter.com/janedoe',
				username: 'test36',
			},
			{
				social: 'linkedin',
				url: 'https://twitter.com/janedoe',
				username: 'test38',
			},
			{
				social: 'facebook',
				url: 'https://twitter.com/janedoe',
				username: 'test38',
			},
			{
				social: 'pinterest',
				url: 'https://twitter.com/janedoe',
				username: 'test38',
			},
			{
				social: 'spotify',
				url: 'https://twitter.com/janedoe',
				username: 'test38',
			},
			{
				social: 'tiktok',
				url: 'https://twitter.com/janedoe',
				username: 'test38',
			},
		],
		followingAccounts: ['user_002', 'user_003', 'user_004'],
		followerAccounts: [
			'user_001',
			'user_002',
			'user_003',
			'user_004',
			'user_005',
		],
	},
	preferences: {
		language: 'en',
		darkTheme: true,
	},
	stats: {
		experiencePoints: 32,
		attendedChallenges: [
			{
				challengeId: 'challenge_23',
				entryId: 'entry_006',
				userId: 'user_006',
				saved: false,
			},
			{
				challengeId: 'challenge_12',
				entryId: 'entry_007',
				userId: 'user_006',
				imageId: 'image_365',
				saved: true,
			},
			{
				challengeId: 'challenge_21',
				entryId: 'entry_008',
				userId: 'user_006',
				imageId: 'image_386',
				rank: 76,
				likes: [
					'user_002',
					'user_003',
					'user_004',
					'user_006',
					'user_011',
					'user_012',
					'user_013',
					'user_014',
					'user_015',
				],
				saved: false,
			},
			{
				challengeId: 'challenge_54',
				entryId: 'entry_009',
				userId: 'user_006',
				imageId: 'image_943',
				rank: 2,
				likes: [
					'user_002',
					'user_003',
					'user_004',
					'user_006',
					'user_011',
					'user_012',
					'user_013',
					'user_014',
					'user_015',
				],
				saved: false,
			},
			{
				challengeId: 'challenge_25',
				entryId: 'entry_010',
				userId: 'user_006',
				imageId: 'image_243',
				rank: 64,
				likes: [
					'user_002',
					'user_003',
					'user_004',
					'user_006',
					'user_011',
					'user_012',
					'user_013',
					'user_014',
					'user_015',
				],
				saved: false,
			},
			{
				challengeId: 'challenge_73',
				entryId: 'entry_011',
				userId: 'user_006',
				imageId: 'image_265',
				rank: 24,
				likes: [
					'user_002',
					'user_003',
					'user_004',
					'user_006',
					'user_011',
					'user_012',
					'user_013',
					'user_014',
					'user_015',
				],
				saved: false,
			},
			{
				challengeId: 'challenge_28',
				entryId: 'entry_012',
				userId: 'user_006',
				imageId: 'image_286',
				rank: 9,
				likes: [
					'user_002',
					'user_003',
					'user_004',
					'user_006',
					'user_011',
					'user_012',
					'user_013',
					'user_014',
					'user_015',
				],
				saved: true,
			},
			{
				challengeId: 'challenge_56',
				entryId: 'entry_013',
				userId: 'user_006',
				imageId: 'image_243',
				rank: 12,
				likes: [
					'user_002',
					'user_003',
					'user_004',
					'user_006',
					'user_011',
					'user_012',
					'user_013',
					'user_014',
					'user_015',
				],
				saved: true,
			},
		],
	},
	auth: {
		authToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
		refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ8',
	},
};
