import { UserState } from '../stores/StoreTypes';

export const dummyUsers: UserState[] = [
	{
		personalInfo: {
			id: 'user_001',
			name: 'Alice Johnson',
			username: 'alice_j',
			email: 'alice.johnson@example.com',
			imageId: 'image_333',
			verified: true,
			premium: false,
		},
		quotas: {
			leftAdQuota: 15,
			leftFreeImageQuota: 3,
		},
		social: {
			socialMedia: [
				{
					social: 'instagram',
					url: 'https://instagram.com/alicej',
					username: 'alice_j',
				},
				{
					social: 'twitter',
					url: 'https://twitter.com/alicej',
					username: 'alice_j',
				},
			],
			followingAccounts: ['user_002', 'user_003'],
			followerAccounts: ['user_006', 'user_004'],
		},
		preferences: {
			language: 'en',
			darkTheme: false,
		},
		stats: {
			experiencePoints: 20,
			attendedChallenges: [
				{
					challengeId: 'challenge_12',
					entryId: 'entry_001',
					userId: 'user_001',
					imageId: 'image_365',
					rank: 12,
					likes: ['user_002', 'user_003', 'user_006'],
					saved: false,
				},
			],
		},
		auth: {
			authToken: 'token_001',
			refreshToken: 'refresh_001',
		},
	},
	{
		personalInfo: {
			id: 'user_002',
			name: 'Bob Smith',
			username: 'bobsmith23',
			email: 'bob.smith@example.com',
			imageId: 'image_365',
			verified: false,
			premium: false,
		},
		quotas: {
			leftAdQuota: 10,
			leftFreeImageQuota: 1,
		},
		social: {
			socialMedia: [
				{
					social: 'twitter',
					url: 'https://twitter.com/bobsmith',
					username: 'bobby',
				},
			],
			followingAccounts: ['user_001', 'user_006'],
			followerAccounts: ['user_003', 'user_004'],
		},
		preferences: {
			language: 'turkish',
			darkTheme: true,
		},
		stats: {
			experiencePoints: 15,
			attendedChallenges: [
				{
					challengeId: 'challenge_23',
					entryId: 'entry_002',
					userId: 'user_002',
					imageId: 'image_243',
					rank: 20,
					likes: ['user_001', 'user_006'],
					saved: true,
				},
			],
		},
		auth: {
			authToken: 'token_002',
			refreshToken: 'refresh_002',
		},
	},
	{
		personalInfo: {
			id: 'user_003',
			name: 'Charlie Lee',
			username: 'charlielee',
			email: 'charlie.lee@example.com',
			imageId: 'image_386',
			verified: true,
			premium: true,
		},
		quotas: {
			leftAdQuota: 18,
			leftFreeImageQuota: 5,
		},
		social: {
			socialMedia: [
				{
					social: 'youtube',
					url: 'https://youtube.com/charlielee',
					username: 'charl33',
				},
			],
			followingAccounts: ['user_002'],
			followerAccounts: ['user_001', 'user_006'],
		},
		preferences: {
			language: 'en',
			darkTheme: true,
		},
		stats: {
			experiencePoints: 50,
			attendedChallenges: [
				{
					challengeId: 'challenge_54',
					entryId: 'entry_003',
					userId: 'user_003',
					imageId: 'image_943',
					rank: 5,
					likes: ['user_002', 'user_006'],
					saved: false,
				},
			],
		},
		auth: {
			authToken: 'token_003',
			refreshToken: 'refresh_003',
		},
	},
	{
		personalInfo: {
			id: 'user_004',
			name: 'Diana Prince',
			username: 'wonderd',
			email: 'diana.prince@example.com',
			imageId: 'image_943',
			verified: true,
			premium: false,
		},
		quotas: {
			leftAdQuota: 9,
			leftFreeImageQuota: 2,
		},
		social: {
			socialMedia: [
				{
					social: 'linkedin',
					url: 'https://linkedin.com/in/dianap',
					username: 'diana_p',
				},
			],
			followingAccounts: ['user_001', 'user_003'],
			followerAccounts: ['user_002', 'user_006'],
		},
		preferences: {
			language: 'en',
			darkTheme: false,
		},
		stats: {
			experiencePoints: 42,
			attendedChallenges: [
				{
					challengeId: 'challenge_25',
					entryId: 'entry_004',
					userId: 'user_004',
					imageId: 'image_243',
					rank: 16,
					likes: ['user_006', 'user_003'],
					saved: true,
				},
			],
		},
		auth: {
			authToken: 'token_004',
			refreshToken: 'refresh_004',
		},
	},
	{
		personalInfo: {
			id: 'user_005',
			name: 'Ethan Brown',
			username: 'ethanb',
			email: 'ethan.brown@example.com',
			imageId: 'image_243',
			verified: false,
			premium: true,
		},
		quotas: {
			leftAdQuota: 20,
			leftFreeImageQuota: 0,
		},
		social: {
			socialMedia: [
				{
					social: 'facebook',
					url: 'https://facebook.com/ethanb',
					username: 'ethanb',
				},
			],
			followingAccounts: ['user_001', 'user_006'],
			followerAccounts: ['user_002', 'user_004'],
		},
		preferences: {
			language: 'en',
			darkTheme: true,
		},
		stats: {
			experiencePoints: 30,
			attendedChallenges: [
				{
					challengeId: 'challenge_28',
					entryId: 'entry_005',
					userId: 'user_005',
					imageId: 'image_286',
					rank: 8,
					likes: ['user_006', 'user_003', 'user_001'],
					saved: false,
				},
			],
		},
		auth: {
			authToken: 'token_005',
			refreshToken: 'refresh_005',
		},
	},
	{
		personalInfo: {
			id: 'user_006',
			name: 'Jane Doe',
			username: 'jane_doe32',
			email: 'jane.doe@example.com',
			imageId: 'image_943',
			verified: true,
			premium: true,
		},
		quotas: {
			leftAdQuota: 12,
			leftFreeImageQuota: 2,
		},
		social: {
			socialMedia: [
				{
					social: 'instagram',
					url: 'https://instagram.com/janedoe',
					username: 'gsfjeh',
				},
				{
					social: 'twitter',
					url: 'https://twitter.com/janedoe',
					username: 'gsfjeh',
				},
			],
			followingAccounts: ['user_002', 'user_003', 'user_004'],
			followerAccounts: ['user_001', 'user_003', 'user_004', 'user_005'],
		},
		preferences: {
			language: 'en',
			darkTheme: true,
		},
		stats: {
			experiencePoints: 32,
			attendedChallenges: [
				{
					challengeId: 'challenge_23',
					entryId: 'entry_006',
					userId: 'user_006',
					imageId: 'image_333',
					rank: 3,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: false,
				},
				{
					challengeId: 'challenge_12',
					entryId: 'entry_007',
					userId: 'user_006',
					imageId: 'image_365',
					saved: true,
				},
				{
					challengeId: 'challenge_21',
					entryId: 'entry_008',
					userId: 'user_006',
					imageId: 'image_386',
					rank: 76,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: false,
				},
				{
					challengeId: 'challenge_54',
					entryId: 'entry_009',
					userId: 'user_006',
					imageId: 'image_943',
					rank: 2,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: false,
				},
				{
					challengeId: 'challenge_25',
					entryId: 'entry_010',
					userId: 'user_006',
					imageId: 'image_243',
					rank: 64,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: false,
				},
				{
					challengeId: 'challenge_73',
					entryId: 'entry_011',
					userId: 'user_006',
					imageId: 'image_265',
					rank: 24,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: false,
				},
				{
					challengeId: 'challenge_28',
					entryId: 'entry_012',
					userId: 'user_006',
					imageId: 'image_286',
					rank: 9,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: true,
				},
				{
					challengeId: 'challenge_56',
					entryId: 'entry_013',
					userId: 'user_006',
					imageId: 'image_243',
					rank: 12,
					likes: [
						'user_002',
						'user_003',
						'user_004',
						'user_006',
						'user_011',
						'user_012',
						'user_013',
						'user_014',
						'user_015',
					],
					saved: true,
				},
			],
		},
		auth: {
			authToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9',
			refreshToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ8',
		},
	},
	{
		personalInfo: {
			id: 'user_007',
			name: 'Frank Miller',
			username: 'frankm',
			email: 'frank.m@example.com',
			imageId: 'image_265',
			verified: false,
			premium: false,
		},
		quotas: { leftAdQuota: 11, leftFreeImageQuota: 4 },
		social: {
			socialMedia: [
				{
					social: 'discord',
					url: 'https://discord.com/frankm',
					username: 'frankm#0921',
				},
			],
			followingAccounts: ['user_006'],
			followerAccounts: ['user_003'],
		},
		preferences: { language: 'german', darkTheme: true },
		stats: {
			experiencePoints: 14,
			attendedChallenges: [
				{
					challengeId: 'challenge_73',
					entryId: 'entry_007',
					userId: 'user_007',
					imageId: 'image_243',
					rank: 44,
					likes: ['user_006', 'user_001'],
					saved: true,
				},
			],
		},
		auth: { authToken: 'token_007', refreshToken: 'refresh_007' },
	},
	{
		personalInfo: {
			id: 'user_008',
			name: 'Grace Park',
			username: 'gracey',
			email: 'grace.park@example.com',
			imageId: 'image_286',
			verified: true,
			premium: false,
		},
		quotas: { leftAdQuota: 7, leftFreeImageQuota: 2 },
		social: {
			socialMedia: [
				{
					social: 'pinterest',
					url: 'https://pinterest.com/gracey',
					username: 'gracey',
				},
			],
			followingAccounts: ['user_002', 'user_005'],
			followerAccounts: ['user_006', 'user_007'],
		},
		preferences: { language: 'en', darkTheme: true },
		stats: {
			experiencePoints: 10,
			attendedChallenges: [],
		},
		auth: { authToken: 'token_008', refreshToken: 'refresh_008' },
	},
	{
		personalInfo: {
			id: 'user_009',
			name: 'Henry Cavill',
			username: 'hencav',
			email: 'henry.c@example.com',
			imageId: 'image_243',
			verified: true,
			premium: true,
		},
		quotas: { leftAdQuota: 5, leftFreeImageQuota: 1 },
		social: {
			socialMedia: [
				{
					social: 'tiktok',
					url: 'https://tiktok.com/@hencav',
					username: 'hencav',
				},
			],
			followingAccounts: ['user_004'],
			followerAccounts: ['user_006'],
		},
		preferences: { language: 'spanish', darkTheme: false },
		stats: {
			experiencePoints: 22,
			attendedChallenges: [],
		},
		auth: { authToken: 'token_009', refreshToken: 'refresh_009' },
	},
	{
		personalInfo: {
			id: 'user_010',
			name: 'Isabella Garcia',
			username: 'isagar',
			email: 'isabella.g@example.com',
			imageId: 'image_333',
			verified: false,
			premium: false,
		},
		quotas: { leftAdQuota: 8, leftFreeImageQuota: 3 },
		social: {
			socialMedia: [
				{
					social: 'spotify',
					url: 'https://spotify.com/isagar',
					username: 'isa',
				},
			],
			followingAccounts: ['user_001', 'user_002'],
			followerAccounts: ['user_006'],
		},
		preferences: { language: 'en', darkTheme: true },
		stats: {
			experiencePoints: 19,
			attendedChallenges: [],
		},
		auth: { authToken: 'token_010', refreshToken: 'refresh_010' },
	},
	{
		personalInfo: {
			id: 'user_011',
			name: 'Jack Wilson',
			username: 'jackw',
			email: 'jack.w@example.com',
			imageId: 'image_365',
			verified: true,
			premium: false,
		},
		quotas: { leftAdQuota: 12, leftFreeImageQuota: 2 },
		social: {
			socialMedia: [
				{
					social: 'twitter',
					url: 'https://twitter.com/jackw',
					username: 'jack',
				},
			],
			followingAccounts: ['user_006'],
			followerAccounts: ['user_005'],
		},
		preferences: { language: 'en', darkTheme: false },
		stats: { experiencePoints: 25, attendedChallenges: [] },
		auth: { authToken: 'token_011', refreshToken: 'refresh_011' },
	},
	{
		personalInfo: {
			id: 'user_012',
			name: 'Karen Taylor',
			username: 'karent',
			email: 'karen.t@example.com',
			imageId: 'image_386',
			verified: false,
			premium: true,
		},
		quotas: { leftAdQuota: 14, leftFreeImageQuota: 3 },
		social: {
			socialMedia: [
				{
					social: 'linkedin',
					url: 'https://linkedin.com/in/karent',
					username: 'karent',
				},
			],
			followingAccounts: ['user_002', 'user_006'],
			followerAccounts: ['user_004'],
		},
		preferences: { language: 'en', darkTheme: true },
		stats: { experiencePoints: 30, attendedChallenges: [] },
		auth: { authToken: 'token_012', refreshToken: 'refresh_012' },
	},
	{
		personalInfo: {
			id: 'user_013',
			name: 'Liam Anderson',
			username: 'liama',
			email: 'liam.a@example.com',
			imageId: 'image_943',
			verified: true,
			premium: false,
		},
		quotas: { leftAdQuota: 6, leftFreeImageQuota: 2 },
		social: {
			socialMedia: [
				{
					social: 'instagram',
					url: 'https://instagram.com/liama',
					username: 'liama',
				},
			],
			followingAccounts: ['user_006'],
			followerAccounts: ['user_001'],
		},
		preferences: { language: 'en', darkTheme: false },
		stats: { experiencePoints: 12, attendedChallenges: [] },
		auth: { authToken: 'token_013', refreshToken: 'refresh_013' },
	},
	{
		personalInfo: {
			id: 'user_014',
			name: 'Mia Chen',
			username: 'miachen',
			email: 'mia.chen@example.com',
			imageId: 'image_243',
			verified: false,
			premium: false,
		},
		quotas: { leftAdQuota: 9, leftFreeImageQuota: 2 },
		social: {
			socialMedia: [
				{
					social: 'discord',
					url: 'https://discord.com/miachen',
					username: 'mia#8890',
				},
			],
			followingAccounts: ['user_003'],
			followerAccounts: ['user_006'],
		},
		preferences: { language: 'chinese', darkTheme: true },
		stats: { experiencePoints: 16, attendedChallenges: [] },
		auth: { authToken: 'token_014', refreshToken: 'refresh_014' },
	},
	{
		personalInfo: {
			id: 'user_015',
			name: 'Noah Davis',
			username: 'noahd',
			email: 'noah.d@example.com',
			imageId: 'image_265',
			verified: true,
			premium: true,
		},
		quotas: { leftAdQuota: 5, leftFreeImageQuota: 1 },
		social: {
			socialMedia: [
				{
					social: 'facebook',
					url: 'https://facebook.com/noahd',
					username: 'noah',
				},
			],
			followingAccounts: ['user_002'],
			followerAccounts: ['user_006', 'user_005'],
		},
		preferences: { language: 'en', darkTheme: false },
		stats: { experiencePoints: 40, attendedChallenges: [] },
		auth: { authToken: 'token_015', refreshToken: 'refresh_015' },
	},
	{
		personalInfo: {
			id: 'user_016',
			name: 'Nathan Brown',
			username: 'nabrwn',
			email: 'noah.d@example.com',
			imageId: 'image_265',
			verified: true,
			premium: true,
		},
		quotas: { leftAdQuota: 5, leftFreeImageQuota: 1 },
		social: {
			socialMedia: [
				{
					social: 'facebook',
					url: 'https://facebook.com/noahd',
					username: 'noah',
				},
			],
			followingAccounts: ['user_002'],
			followerAccounts: ['user_006', 'user_005'],
		},
		preferences: { language: 'en', darkTheme: false },
		stats: { experiencePoints: 40, attendedChallenges: [] },
		auth: { authToken: 'token_015', refreshToken: 'refresh_015' },
	},
];
